version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
     - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=60

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - browserTimeout=30
    ports:
      - "5900:5900"

  chrome2:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - browserTimeout=30
    ports:
      - "5902:5900"

  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - browserTimeout=30
    ports:
      - "5901:5900"

  uitests:
    image: uitests
    depends_on:
      - chrome